### PR TITLE
Fix monitoring processes from elements

### LINKED ISSUE #185: Fix monitoring from element
Fix from ec4ba2f4790ec5239614704498bc1e93c6709ad5 has to applied to master

### PR DESCRIPTION
**Pull request by Hajto**
Closes #185

### CODE REVIEW

File: test/membrane/core/element_test.exs [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  describe "Not linked element" do
+    test "should shutdown when pipeline is down" do
+      monitored_proc = spawn(fn -> receive do: (:exit -> :ok) end)
+
+      {:ok, elem_pid} =
+        monitored_proc
+        |> element_init_options
+        |> Element.start()
+
+      {:ok, _clock} = Message.call(elem_pid, :handle_watcher, self())
```
Comment (Hajto) [inline test/membrane/core/element_test.exs]: This line works same as `:ok = Element.set_watcher(elem_pid, self())` (based on my archeology work).
First when making this PR I disabled it because I couldn't find the proper substitute at first and this test passed without this line. If I understand watcher correctly, element will notify the watcher when it gets a down message?

Maybe we should refute?

File: test/membrane/core/element_test.exs [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+      ref = Process.monitor(elem_pid)
+      send(monitored_proc, :exit)
+      assert_receive {:DOWN, ^ref, :process, ^elem_pid, :normal}
+    end
+
+    test "should not assume pipeline is down when getting any monitor message" do
+      monitored_proc = spawn(fn -> receive do: (:exit -> :ok) end)
```
Comment (Hajto) [inline test/membrane/core/element_test.exs]: Why are we creating here `monitored_proc` if it isn't used anywhere further in the test. Do we want to have process that is alive during test execution and keep test executor mailbox sane?

File: test/membrane/core/element_test.exs (hunk 1 above)
Comment (bblaszkow06) [reply test/membrane/core/element_test.exs]: There's no such wrapper in v0.4.0, you can create one ;) `:handle_watcher` is basically `:set_watcher` but returns a clock as well

File: test/membrane/core/element_test.exs (hunk 2 above)
Comment (bblaszkow06) [reply test/membrane/core/element_test.exs]: `monitored_proc` is needed for elemtent to set up watcher, but it can be `self()` as well

File: lib/membrane/core/element.ex [hunk 3]
```diff
@@ -130,8 +130,8 @@ defmodule Membrane.Core.Element do
 
   @impl GenServer
   def init(options) do
-    Process.monitor(options.pipeline)
-    state = State.new(options)
+    parent_monitor = Process.monitor(options.pipeline)
```
Comment (bblaszkow06) [inline lib/membrane/core/element.ex]: Let's change `pipeline` to `parent` or `parent_process` to be consistent with state struct field name and make it ready for bins
