### PR TITLE
Fix/pad ref

### LINKED ISSUE #44: Change pad declarations
- [x] dynamic pads:
```elixir
{{:dynamic, pad_name}, {availability, mode, caps}}
```
to
```elixir
pad_name: {:on_request, mode, caps}
```

- [ ]  demand unit in sinks:
```elixir
sink_pad_name:  {availability, {:pull, demand_in: :buffers}, caps}
```
to
```elixir
sink_pad_name:  [availability: :cos, caps: adkald, mode: :pull, demand_in: :buffers]
```

### PR DESCRIPTION
**Pull request by mat-hek**
Closes #44

### CODE REVIEW

File: lib/membrane/element/action.ex [hunk 1]
```diff
@@ -95,9 +95,9 @@ defmodule Membrane.Element.Action do
           {:demand, demand_common_payload_t | demand_filter_payload_t | demand_sink_payload_t}
 
   @type demand_filter_payload_t ::
-          {Pad.name_t(), {:source, Pad.name_t()} | :self, size :: non_neg_integer}
-  @type demand_sink_payload_t :: {Pad.name_t(), {:set_to, size :: non_neg_integer}}
-  @type demand_common_payload_t :: Pad.name_t() | {Pad.name_t(), size :: non_neg_integer}
+          {Pad.ref_t(), {:source, Pad.ref_t()} | :self, size :: non_neg_integer}
+  @type demand_sink_payload_t :: {Pad.ref_t(), {:set_to, size :: non_neg_integer}}
```
Comment (bblaszkow06) [inline lib/membrane/element/action.ex]: These types are invalid after #94

File: lib/membrane/pipeline/state.ex [hunk 2]
```diff
@@ -14,9 +14,9 @@ defmodule Membrane.Pipeline.State do
   @type t :: %__MODULE__{
           internal_state: internal_state_t | nil,
           playback: Playback.t(),
-          module: module,
+          module: module | nil,
```
Comment (bblaszkow06) [inline lib/membrane/pipeline/state.ex]: Shouldn't that always be something other than `nil`
