### PR TITLE
Fixed vocabulary in Membrane.Testing.Assertions docs.

### LINKED ISSUE #186: Invalid vocabulary in Membrane.Testing.Assertions docs
Looking at guide update, I realised docs for assert_(start/end)_of_stream claim that pipeline receives `events` this is imprecise as only elements receive events, pipelines can only get notifications

### PR DESCRIPTION
**Pull request by Hajto**
Closes #186

### CODE REVIEW

File: lib/membrane/testing/assertions.ex [hunk 1]
```diff
@@ -353,9 +353,9 @@ defmodule Membrane.Testing.Assertions do
   end
 
   @doc """
-  Asserts that `Membrane.Testing.Pipeline` received or is going to receive
-  end_of_stream event from the element with name `element_name` within the `timeout`
-  period specified in milliseconds.
+  Asserts that `Membrane.Testing.Pipeline` received or is going to receive end_of_stream
+  notification about from the element with its name `element_name` within the `timeout` period
```
Comment (bblaszkow06) [inline lib/membrane/testing/assertions.ex]: about from?

File: lib/membrane/testing/assertions.ex [hunk 2]
```diff
@@ -333,9 +333,9 @@ defmodule Membrane.Testing.Assertions do
   end
 
   @doc """
-  Asserts that `Membrane.Testing.Pipeline` received or is going to receive
-  start_of_stream event from the element with element `element_name` within the
-  `timeout` period specified in milliseconds.
+  Asserts that `Membrane.Testing.Pipeline` received or is going to receive start_of_stream
+  notification from the element with its name `element_name` within the `timeout` period
```
Comment (bblaszkow06) [inline lib/membrane/testing/assertions.ex]: `its name`? rather `with a name`

File: lib/membrane/testing/assertions.ex (hunk 1 above)
Comment (bblaszkow06) [reply lib/membrane/testing/assertions.ex]: `its name`? rather `with a name`
