### PR TITLE
Fix issues related to action handling

### LINKED ISSUE #42: Sending any message from an element in stopped state to another element should be forbidden
In `stopped` state pads may simply be not yet linked, so sending any message then causes a RC

### PR DESCRIPTION
**Pull request by bblaszkow06**
Closes #42

### CODE REVIEW

**Comment by bblaszkow06** [comment]
@mat-hek There are couple more fixes I will add to this PR, but to keep the diff relatively small they will be added as separate PR's (that will be merged to this branch)

File: test/membrane/pipeline_test.exs [hunk 1]
```diff
@@ -11,26 +11,28 @@ defmodule Membrane.PipelineTest do
...
       state = %State{state | children: %{a: self()}}
 
-      assert {{:error, {:cannot_handle_spec, {:duplicate_element_names, [:a]}}}, _state} =
-               @module.handle_action(
-                 {:spec, %Spec{children: [a: :child]}},
-                 nil,
-                 [],
-                 state
-               )
+      assert_raise Membrane.PipelineError, ~r/.*[Dd]uplicate.*\[:a\]/, fn ->
```
Comment (mat-hek) [inline test/membrane/pipeline_test.exs]: make case insensitive

File: test/membrane/pipeline_test.exs [hunk 2]
```diff
@@ -11,26 +11,28 @@ defmodule Membrane.PipelineTest do
...
-    test "should return error if duplicate elements exist in spec", %{state: state} do
-      assert {{:error, {:cannot_handle_spec, {:duplicate_element_names, [:a]}}}, _state} =
-               @module.handle_action(
-                 {:spec, %Spec{children: [a: :child1, a: :child2]}},
-                 nil,
-                 [],
-                 state
-               )
+    test "should raise if duplicate elements exist in spec", %{state: state} do
+      assert_raise Membrane.PipelineError, ~r/.*[Dd]uplicate.*\[:a\]/, fn ->
```
Comment (mat-hek) [inline test/membrane/pipeline_test.exs]: you can add `i` flag to make the regex case insensitive instead of `[Dd]`

File: test/support/caps_mock.ex [hunk 3]
```diff
@@ -0,0 +1,3 @@
+defmodule Membrane.Caps.Mock do
```
Comment (mat-hek) [inline test/support/caps_mock.ex]: is this used anywhere?

Comment (bblaszkow06) [reply test/support/caps_mock.ex]: https://github.com/membraneframework/membrane-core/pull/156/files#diff-10829bba6f1c3fbe5a75fbdbb706c84f

File: lib/membrane/pipeline.ex [hunk 4]
```diff
@@ -273,30 +253,29 @@ defmodule Membrane.Pipeline do
...
     end
   end
 
-  @spec parse_children(Spec.children_spec_t() | any) :: Type.try_t([parsed_child_t])
+  @spec parse_children(Spec.children_spec_t() | any) :: [parsed_child_t]
   defp parse_children(children) when is_map(children) or is_list(children),
-    do: children |> Bunch.Enum.try_map(&parse_child/1)
+    do: children |> Enum.map(&parse_child/1)
 
-  @spec parse_child(any) :: Type.try_t(parsed_child_t)
```
[the remark this answers is not in the document]
Comment (bblaszkow06) [reply lib/membrane/pipeline.ex]: For private function? `parse_children` has one and that's enough, the rest can be handled by dialyzer
